executor: LocalExecutor

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/Kimwonjoon/Twilight_dags.git
    branch: main
    subPath: "dags"

logs:
  persistence:
    enabled: false
